34,71c34,36
< 	@if [ -f GNUmakefile ]; then \
< 	    echo "***"; \
< 	    echo "*** You are not using the GNU version of Make - maybe it's called gmake"; \
< 	    echo "*** or it's in a different PATH? Please read INSTALL." ; \
< 	    echo "***"; \
< 	    exit 1; \
< 	 elif test -n "$(HOST_ARCH)"  && test -z "$(MAKE_VERSION)" ; then \
< 	    echo "***"; \
< 	    echo "*** You are not using GNU Make on Solaris, please make sure you do" ; \
< 	    echo "*** and re-run 'make' "; \
< 	    echo "***"; \
< 	    exit 1 ; \
< 	 elif test -n "$(MACHINE_ARCH)"  && test -z "$(MAKE_VERSION)" ; then \
< 	    echo "***"; \
< 	    echo "*** You are not using GNU Make on FreeBSD, please make sure you do" ; \
< 	    echo "*** and re-run 'make' "; \
< 	    echo "***"; \
< 	    exit 1 ; \
< 	 else \
< 	    echo "***"; \
< 	    echo "*** To build this program, you must run"; \
< 	    echo "*** autoheader && autoconf && ./configure and then run GNU make."; \
< 	    echo "***"; \
< 	    echo -n "*** Shall I do this for you now? (y/n) "; \
< 	    read answer; \
< 	    if [ "$$answer" = "y" ]; then \
< 		autoheader && autoconf && ./configure || exit 1; \
< 	  	if $(GNU_MAKE_CMD) -v |grep GNU >/dev/null 2>/dev/null; then \
< 		   $(GNU_MAKE_CMD) ;\
< 		elif $(MAKE_CMD) -v |grep GNU >/dev/null 2>/dev/null; then \
< 		   $(MAKE_CMD) ;\
< 		else \
< 		   echo "Neither 'make' nor 'gmake' are GNU compatible!" ; \
< 		   echo "Please read INSTALL." ; \
< 		   exit 1 ; \
< 		fi ;\
< 	    fi; \
< 	 fi
---
> 	# In Solus this always occurs
> 	autoheader && autoconf && ./configure || exit 1; \
> 	$(GNU_MAKE_CMD) ;
